In [1]:
import torch
from torch_openreml.covariance.transform import TransformExpPow2

t = TransformExpPow2()
x = torch.tensor([0.0, 1.0])
t(x)

tensor([1.0000, 7.3891])

In [2]:
import torch
from torch_openreml.covariance.transform import TransformExpPow2

t = TransformExpPow2()
x = torch.tensor([1.0])
t.inverse(x)

tensor([0.])

In [3]:
import torch
from torch_openreml.covariance.transform import TransformExpPow2

t = TransformExpPow2()
x = torch.tensor([0.0, 1.0])
t.grad(x)

tensor([ 2.0000, 14.7781])