In [1]:
import torch
from torch_openreml.covariance.transform import TransformExp10

t = TransformExp10()
x = torch.tensor([0.0, 1.0])
t(x)

tensor([ 1., 10.])

In [2]:
import torch
from torch_openreml.covariance.transform import TransformExp10

t = TransformExp10()
x = torch.tensor([1.0, 10.0])
t.inverse(x)

tensor([0., 1.])

In [3]:
import torch
from torch_openreml.covariance.transform import TransformExp10

t = TransformExp10()
x = torch.tensor([1.0])
t.grad(x)

tensor([23.0259])