In [1]:
import torch
from torch_openreml.covariance import SimpleMatrix

def my_v(free_params):
    return torch.diag(free_params)

mat = SimpleMatrix(num_free_params=3, call=my_v, default=torch.tensor([1.0]))
mat(torch.tensor([1.0, 2.0, 3.0]))

tensor([[1., 0., 0.],
        [0., 2., 0.],
        [0., 0., 3.]])

In [2]:
mat()

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [3]:
mat({
    "theta_0": torch.tensor([2.0]),
    "theta_1": torch.tensor([3.0]),
    "theta_2": torch.tensor([4.0]),
})

tensor([[2., 0., 0.],
        [0., 3., 0.],
        [0., 0., 4.]])

In [4]:
mat.grad(torch.tensor([1.0, 2.0, 3.0]))

/opt/homebrew/Caskroom/miniconda/base/envs/torch-openreml/lib/python3.12/site-packages/torch/jit/_script.py:1491: FutureWarning: `torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`.
  warnings.warn(


(tensor([[[1., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 1., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 1.]]]),
 ['theta_0', 'theta_1', 'theta_2'])