In [1]:
from torch_openreml.covariance import DummyMatrix

rep = ["rep1", "rep2", "rep2"]
block = ["block1", "block2", "block1"]

mat = DummyMatrix(rep, block)
print(mat())
print(mat.colnames)

tensor([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]])
['rep1⋈block1', 'rep1⋈block2', 'rep2⋈block1', 'rep2⋈block2']


In [2]:
mat = DummyMatrix(rep, block, drop_first=True)
print(mat())
print(mat.colnames)

tensor([[0., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]])
['rep1⋈block2', 'rep2⋈block1', 'rep2⋈block2']


In [3]:
mat = DummyMatrix(rep, block, levels=[["rep1", "rep2", "rep3"], ["block1", "block2"]])
print(mat())
print(mat.colnames)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0.]])
['rep1⋈block1', 'rep1⋈block2', 'rep2⋈block1', 'rep2⋈block2', 'rep3⋈block1', 'rep3⋈block2']


In [4]:
mat = DummyMatrix(rep, block, levels=[["rep3", "rep1"], ["block1", "block2"]], lex_order=False)
print(mat())
print(mat.colnames)

tensor([[0., 0., 1., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
['rep3⋈block1', 'rep3⋈block2', 'rep1⋈block1', 'rep1⋈block2']


/Users/patrickli/Desktop/rproj/torch-openreml/torch_openreml/covariance/dummy_matrix.py:117: RuntimeWarning: Unknown combination ('rep2', 'block2') dropped!
  warnings.warn(f"Unknown combination {r} dropped!", RuntimeWarning)
/Users/patrickli/Desktop/rproj/torch-openreml/torch_openreml/covariance/dummy_matrix.py:117: RuntimeWarning: Unknown combination ('rep2', 'block1') dropped!
  warnings.warn(f"Unknown combination {r} dropped!", RuntimeWarning)


In [5]:
mat = DummyMatrix(rep, block, levels=[["rep2", "rep1"], ["block1", "block2"]], lex_order=False, drop_empty_cols=True)
print(mat())
print(mat.colnames)

tensor([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]])
['rep2⋈block1', 'rep2⋈block2', 'rep1⋈block1']


In [6]:
import torch
from torch_openreml.covariance import DummyMatrix

rep = ["rep1", "rep2", "rep2"]
mat = DummyMatrix(rep)
mat()

tensor([[1., 0.],
        [0., 1.],
        [0., 1.]])

In [7]:
mat(torch.tensor([], dtype=torch.float64))

tensor([[1., 0.],
        [0., 1.],
        [0., 1.]], dtype=torch.float64)