In [1]:
import torch
from torch_openreml.covariance import Gram, LowerTriangularMatrix

x = LowerTriangularMatrix(3, 2)
op = Gram(x, gram_type="xtx")
op()

tensor([[3., 2.],
        [2., 2.]])

In [2]:
op_xxt = Gram(x, gram_type="xxt")
op_xxt()

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [1., 2., 2.]])

In [3]:
import torch
from torch_openreml.covariance import Gram, LowerTriangularMatrix

x = LowerTriangularMatrix(3, 2)
op = Gram(x, gram_type="xtx")
free_params = torch.tensor([0.0, 0.5, 1.0, 0.2, -0.3])
grad, grad_names = op.manual_grad(free_params)
grad

tensor([[[ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[ 1.0000,  1.0000],
         [ 1.0000,  0.0000]],

        [[ 0.0000,  0.5000],
         [ 0.5000,  2.0000]],

        [[ 0.4000, -0.3000],
         [-0.3000,  0.0000]],

        [[ 0.0000,  0.2000],
         [ 0.2000, -0.6000]]])

In [4]:
grad_names

['op_0/L_0_0', 'op_0/L_1_0', 'op_0/L_1_1', 'op_0/L_2_0', 'op_0/L_2_1']

In [5]:
op_xxt = Gram(x, gram_type="xxt")
grad_xxt, grad_names_xxt  = op_xxt.manual_grad(free_params)
grad_xxt

tensor([[[ 0.0000,  0.5000,  0.2000],
         [ 0.5000,  0.0000,  0.0000],
         [ 0.2000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  1.0000,  0.2000],
         [ 0.0000,  0.2000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  2.0000, -0.3000],
         [ 0.0000, -0.3000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.5000],
         [ 0.0000,  0.5000,  0.4000]],

        [[ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  1.0000],
         [ 0.0000,  1.0000, -0.6000]]])