In [1]:
import torch
from torch_openreml.covariance.transform import TransformExp2

t = TransformExp2()
x = torch.tensor([0.0, 1.0])
t(x)

tensor([1., 2.])

In [2]:
import torch
from torch_openreml.covariance.transform import TransformExp2

t = TransformExp2()
x = torch.tensor([1.0, 2.0])
t.inverse(x)

tensor([0., 1.])

In [3]:
import torch
from torch_openreml.covariance.transform import TransformExp2

t = TransformExp2()
x = torch.tensor([1.0])
t.grad(x)

tensor([1.3863])