In [1]:
import torch
from torch_openreml.covariance import IdentityMatrix

mat = IdentityMatrix(3)
mat()

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [2]:
import torch
from torch_openreml.covariance import IdentityMatrix

mat = IdentityMatrix(3)
mat()

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [3]:
mat(torch.tensor([], dtype=torch.float64))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)