In [1]:
import torch
from torch_openreml.covariance import DummyMatrix, DiagonalMatrix, CovariancePropagation

z = DummyMatrix(["a", "b", "c", "a"])
z()

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

In [2]:
g = DiagonalMatrix(3)
op = CovariancePropagation(z=z, g=g)
free_params = torch.tensor([0.0, 0.5, 1.0])
op(free_params)

tensor([[1.0000, 0.0000, 0.0000, 1.0000],
        [0.0000, 2.7183, 0.0000, 0.0000],
        [0.0000, 0.0000, 7.3891, 0.0000],
        [1.0000, 0.0000, 0.0000, 1.0000]])

In [3]:
import torch
from torch_openreml.covariance import DummyMatrix, DiagonalMatrix, CovariancePropagation

z = DummyMatrix(["a", "b", "c", "a"])
z()

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

In [4]:
g = DiagonalMatrix(3)
op = CovariancePropagation(z=z, g=g)
free_params = torch.tensor([0.0, 0.5, 1.0])
grad, grad_names = op.manual_grad(free_params)
grad

tensor([[[ 2.0000,  0.0000,  0.0000,  2.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 2.0000,  0.0000,  0.0000,  2.0000]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  5.4366,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000, 14.7781,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]])

In [5]:
grad_names

['g/sigma^2_0', 'g/sigma^2_1', 'g/sigma^2_2']