In [1]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
free_params = torch.tensor([0.0, 0.5, 1.0])
params = mat.build_params(free_params)
mat.set_intermediates(params, {"log(sigma^2)/2": torch.log(params) / 2})
mat.get_intermediates(params)

{'log(sigma^2)/2': tensor([0.0000, 0.5000, 1.0000])}

In [2]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
free_params = torch.tensor([0.0, 0.5, 1.0])
params = mat.build_params(free_params)
mat.set_intermediates(params, {"log(sigma^2)/2": torch.log(params) / 2})
mat.get_intermediates(params)

{'log(sigma^2)/2': tensor([0.0000, 0.5000, 1.0000])}

In [3]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
free_params = torch.tensor([0.0, 0.5, 1.0])
params = mat.build_params(free_params)
mat.set_intermediates(params, {"log(sigma^2)/2": torch.log(params) / 2})
print(mat.get_intermediates(params))

{'log(sigma^2)/2': tensor([0.0000, 0.5000, 1.0000])}


In [4]:
mat.reset_intermediates()
print(mat.get_intermediates(free_params))

None


In [5]:
from torch_openreml.covariance import ScalarMatrix

mat = ScalarMatrix(3)
mat.get_default_dtype_device()

(device(type='cpu'), torch.float32)

In [6]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
free_params = torch.tensor([0.0, 0.5, 1.0])
mat.build_params(free_params)

tensor([1.0000, 2.7183, 7.3891])

In [7]:
mat.build_params()

tensor([1., 1., 1.])

In [8]:
mat.param_specs["sigma^2_2"]["fixed"] = True
mat.build_params(free_params[0:2])

tensor([1.0000, 2.7183, 1.0000])

In [9]:
mat.build_params(free_params[0:2], include_fixed=False)

tensor([1.0000, 2.7183])

In [10]:
mat.build_params(free_params[0:2], include_fixed=False, trans=False)

tensor([0.0000, 0.5000])

In [11]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
free_params = torch.tensor([0.0, 0.5, 1.0])
mat.trans_grad(free_params)

tensor([ 2.0000,  5.4366, 14.7781])

In [12]:
mat.trans_grad()

tensor([2., 2., 2.])

In [13]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(2)
free_params = torch.tensor([0.0, 0.5])
grad, grad_names = mat.auto_grad(free_params)
grad, grad_names

/opt/homebrew/Caskroom/miniconda/base/envs/torch-openreml/lib/python3.12/site-packages/torch/jit/_script.py:1491: FutureWarning: `torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`.
  warnings.warn(


(tensor([[[2.0000, 0.0000],
          [0.0000, 0.0000]],
 
         [[0.0000, 0.0000],
          [0.0000, 5.4366]]]),
 ['sigma^2_0', 'sigma^2_1'])

In [14]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(2)
free_params = torch.tensor([0.0, 0.5])
grad, grad_names = mat.grad(free_params)
grad, grad_names

(tensor([[[2.0000, 0.0000],
          [0.0000, 0.0000]],
 
         [[0.0000, 0.0000],
          [0.0000, 5.4366]]]),
 ['sigma^2_0', 'sigma^2_1'])