In [1]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
free_params = torch.tensor([0.0, 0.5, 1.0])
sigma2 = mat.build_params(free_params)
mat.set_intermediates(free_params, {"sigma2": sigma2})
mat.get_intermediates(free_params)

{'sigma2': tensor([1.0000, 2.7183, 7.3891])}

In [2]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
free_params = torch.tensor([0.0, 0.5, 1.0])
sigma2 = mat.build_params(free_params)
mat.set_intermediates(free_params, {"sigma2": sigma2})
mat.get_intermediates(free_params)

{'sigma2': tensor([1.0000, 2.7183, 7.3891])}

In [3]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
free_params = torch.tensor([0.0, 0.5, 1.0])
sigma2 = mat.build_params(free_params)
mat.set_intermediates(free_params, {"sigma2": sigma2})
print(mat.get_intermediates(free_params))
mat.reset_intermediates()
print(mat.get_intermediates(free_params))

{'sigma2': tensor([1.0000, 2.7183, 7.3891])}
None


In [4]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
free_params = torch.tensor([0.0, 0.5, 1.0])
mat.trans_grad(free_params)

tensor([ 2.0000,  5.4366, 14.7781])

In [5]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(2)
free_params = torch.tensor([0.0, 0.5])
grad, grad_names = mat.auto_grad(free_params)
grad, grad_names

(tensor([[[2.0000, 0.0000],
          [0.0000, 0.0000]],
 
         [[0.0000, 0.0000],
          [0.0000, 5.4366]]]),
 ['sigma^2_0', 'sigma^2_1'])

In [6]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(2)
free_params = torch.tensor([0.0, 0.5])
grad, grad_names = mat.grad(free_params)
grad, grad_names

(tensor([[[2.0000, 0.0000],
          [0.0000, 0.0000]],
 
         [[0.0000, 0.0000],
          [0.0000, 5.4366]]]),
 ['sigma^2_0', 'sigma^2_1'])