In [1]:
import torch
from torch_openreml.covariance.transform import TransformExp

t = TransformExp()
x = torch.tensor([0.0, 1.0])
t(x)

tensor([1.0000, 2.7183])

In [2]:
import torch
from torch_openreml.covariance.transform import TransformExp

t = TransformExp()
x = torch.tensor([1.0])
t.inverse(x)

tensor([0.])

In [3]:
import torch
from torch_openreml.covariance.transform import TransformExp

t = TransformExp()
x = torch.tensor([0.0])
t.grad(x)

tensor([1.])